DROP TABLE dishes IF EXISTS;
DROP TABLE votes IF EXISTS;
DROP TABLE menus IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    registered DATETIME     NOT NULL,
    role       VARCHAR(255) NOT NULL,
    CONSTRAINT user_name_email UNIQUE (name, email)
);

CREATE TABLE restaurants
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX restaurants_name_idx ON restaurants (name);

CREATE TABLE menus
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_id INTEGER  NOT NULL,
    date_time     DATETIME NOT NULL,
    CONSTRAINT menus_restaurant_id_datetime UNIQUE (restaurant_id, date_time),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX menus_date_restaurant_idx ON menus (date_time, restaurant_id);

CREATE TABLE votes
(
    id        INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    user_id   INTEGER  NOT NULL,
    menu_id   INTEGER  NOT NULL,
    date_time DATETIME NOT NULL,
    CONSTRAINT votes_user_menu_idx UNIQUE (user_id, menu_id),
    CONSTRAINT votes_user_datetime_idx UNIQUE (user_id, date_time),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (menu_id) REFERENCES menus (id)
);

CREATE TABLE dishes
(
    id           INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    menu_id      INTEGER      NOT NULL,
    price        INTEGER      NOT NULL,
    CONSTRAINT dishes_menu_dish_type_idx UNIQUE (menu_id, name),
    FOREIGN KEY (menu_id) REFERENCES menus (id) ON DELETE CASCADE
);
CREATE INDEX dishes_menu_idx ON dishes (menu_id);